[env]
INSTALL_PREFIX = "/usr/local"
HELIX_DEFAULT_RUNTIME = "{{env.INSTALL_PREFIX}}/lib/helix/runtime"

[tasks.clean]
  description = "Clean"
  run = "cargo clean"

[tasks.build]
  description = "Build"
  run = "cargo build --profile opt --locked --manifest-path helix-term/Cargo.toml"

[tasks.run]
  description = "Run"
  run = "target/opt/hx -a"

[tasks.install]
  description = "Install"
  run = [
    "sudo mv -f ${HELIX_DEFAULT_RUNTIME} ${HELIX_DEFAULT_RUNTIME}.bak || true",
    "sudo cp -r runtime ${INSTALL_PREFIX}/lib/helix/",
    "sudo install --backup=numbered target/opt/hx ${INSTALL_PREFIX}/bin",
  ]
